### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by jimyeong-han** [kris6613123/Weekly-Schedule-Widget#2]
## Main Checklist
- [x]  Basic Design
- [x]  Time-table add implementation
- [x]  To-do list add implementation
- [x]  Data Save & Read
- [x]  Readme Edit

**Comment by jimyeong-han** [comment]
### Detailed Design

- [x]  Time-table class delete implementation
- [ ] More information on the class
- [ ] Color Differentiation 
- [ ] App Icon customize
